<h2><span class="bg-color-4 bg-color-1">Самобытность</span></h2>
<p>
    Сочетаем СМ и ИИ. Системное Мышление + Интуиция и Импровизация. Любим использовать СМ когда есть время и практикуем
    ИИ когда времени нет
</p>
<h2><span class="bg-color-4 bg-color-1">Энергия спокойствия</span></h2>
<p>
    Стремимся поддерживать оптимальный баланс между Вдохновением и Дисциплиной. Находясь в равновесии, делаем живые и
    динамичные работы
</p>
<h2><span class="bg-color-4 bg-color-1">Ассортимент</span></h2>
<p>
    Пишем <a target="_blank" href="/services/napisanie-kommunikatsionnykh-strategiy/">коммуникационные стратегии</a>.
    Разрабатываем <a
            target="_blank" href="/services/razrabotka-kreativnykh-kontseptsiy/">креативные концепции</a>. Делаем <a
            target="_blank" href="/services/art-direkshn/">арт-дирекшн</a>, <a
            target="_blank" href="/services/kopirayting-prodayushchie-teksty/">копирайтинг и
        сторителлинг</a>. Пишем <a target="_blank" href="/services/napisanie-paketov-stsenariev/">сценарии видео- и
        аудио-роликов</a>. Производим
    <a target="_blank" href="/services/proizvodstvo-reklamnykh-rolikov/">рекламные ролики</a>. Создаем <a
            target="_blank" href="/services/sozdanie-illyustratsiy/">уникальные иллюстрации</a>.
    Разрабатываем <a target="_blank" href="/services/razrabotka-logotipov-i-torgovykh-marok/">логотипы и торговые
        марки</a>. Разрабатываем
    <a target="_blank" href="/services/razrabotka-firmennogo-stilya/">фирменный стиль</a>. Разрабатываем <a
            target="_blank" href="/services/razrabotka-brend-bukov/">бренд-буки</a>. Делаем <a target="_blank"
                                                                                               href="/services/razrabotka-katalogov-mnogopolosnykh-izdaniy-i-godovykh-otchetov/">дизайн
        каталогов, многополосных изданий и годовых отчетов</a>. Разрабатываем <a target="_blank"
                                                                   href="/services/razrabotka-broshyur/">брошюры, буклеты и лифлеты</a>. Занимаемся адаптацией,
    переформатированием и созданием новых брендов. Участвуем <a target="_blank"
                                                                href="/services/uchastie-v-kreativnykh-tenderakh/">в
        оплачиваемых креативных тендерах</a>.
</p>
<h2><span class="bg-color-4 bg-color-1">Талисман</span></h2>
<p>
    Всегда с трепетом ждем появления музы-вдохновительницы. Если она не приходит, идем к ней сами. И несем цветок
    чертополоха в руке
</p>
<h2><span class="bg-color-4 bg-color-1">Интерес, парадокс и пропорции</span></h2>
<p>
    Предпочитаем интересную рекламу. Считаем, что даже Hard sell нуждается в небольших дозах Soft sell. Когда уместно, в
    качестве художественного приема используем парадокс. От проекта к проекту стараемся комбинировать рациональное и
    эмоциональное в различных пропорциях
</p>
<h2><span class="bg-color-4 bg-color-1">“Lego”</span></h2>
<p>
    Мы – модульный конструктор из разных специалистов. Можно собрать уникальный набор. Или использовать типовые модули
    для работ, сходных по форме и содержанию. Обычно проекты ведутся базовым сетом сотрудников. Но есть и расширенный
    вариант. А также опция премиум люкс
</p>
<h2><span class="bg-color-4 bg-color-1">Ломка стереотипов</span></h2>
<p>
    Любим смотреть на реальность под всевозможными углами. Выбираться из наезженной колеи. Создавать новые смыслы и
    модели взаимосвязей
</p>
<h2><span class="bg-color-4 bg-color-1">Эпилог</span></h2>
<p>
    Мы не стремимся изменить рынок и мир.<br>
    Хотим чтобы рынок и мир меняли нас самих.<br>
    Хотим новые впечатления. Новый опыт.<br>
    Новые знания. Новых партнеров. Возможно, даже новых друзей.<br>
    И заработать денег.<br>
    Реклама все-таки
</p>